name: BetterItemForceBattle
version: '1.0.0'
main: dev.zaen.itemforcebattle.BetterItemForceBattle
api-version: '1.21'
authors:
  - Zaen
description: Ein Item Force Battle Plugin inspiriert von BastiGHG

commands:
  itemforce:
    description: Hauptcommand für ItemForceBattle
    usage: /<command> <start|stop|setspawn|reload|gui>
    aliases: [if, ifb, bifb]
  skip:
    description: Überspringe dein aktuelles Item
    usage: /skip
  sb:
    description: Scoreboard ein/ausschalten
    usage: /sb

permissions:
  itemforce.admin:
    description: Erlaubt alle Admin-Befehle
    default: op
  itemforce.play:
    description: Erlaubt Spieler-Befehle (skip)
    default: true
